# THIS IS VERY VERY BASIC
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: crossplane
      version: "1.20.0"
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace

# There are a significant amount of providers and other values to finish the complete installation, but for brief discussion, this should suffice