apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluentbit
spec:
  releaseName: fluentbit
  chart:
    spec:
      chart: fluent-bit
      sourceRef:
        kind: HelmRepository
        name: fluentbit
        namespace: flux-system
      version: 0.30.4
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/values.yaml