apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
spec:
  valuesFrom:
    - kind: Secret
      name: actions-runner-controller-github
      valuesKey: runner-pat
      targetPath: authSecret.github_token
  releaseName: actions-runner-controller
  chart:
    spec:
      chart: actions-runner-controller
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      version: v0.23.0
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  # Default values
  # https://github.com/actions-runner-controller/actions-runner-controller/blob/master/charts/actions-runner-controller/values.yaml
  values:
    authSecret:
      create: true
    githubWebhookServer:
      enabled: true
      service:
        type: NodePort
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: alb
          alb.ingress.kubernetes.io/target-type: 'ip'
          alb.ingress.kubernetes.io/scheme: internet-facing
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
          external-dns.alpha.kubernetes.io/hostname: "gh-webhook.dev.devopsidiot.com"
          alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
          alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:174950171951:certificate/7b6eceee-f93a-484e-91fb-88118ac1197e
        hosts:
          - host: gh-webhook.dev.devopsidiot.com
            paths:
              - path: /*
                pathType: ImplementationSpecific
                backend:
                  service:
                    name: actions-runner-controller
                    port:
                      number: 80