apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prod-infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
  - name: prod-sources
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: .
  prune: false
  validation: client
  decryption:
    provider: sops