---
apiVersion: v1
kind: Secret
metadata:
  name: gitops
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/devopsidiot/gitops2024.git
---
apiVersion: v1
kind: Secret
metadata:
  name: devopsidiot-helm-charts
  namespace: argo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/devopsidiot/helm.git
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-devopsidiot-deployment
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/devopsidiot/terraform-modules.git
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-devopsidiot-cronjob
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/devopsidiot/terraform-modules.git
