apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: "https://argocd.rnd.devopsidiot.com"
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $argocd-github:clientid-rnd
          clientSecret: $argocd-github:clientsecret-rnd
          orgs:
          - name: devopsidiot
            teams:
            - DevOps