apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
- runners.yaml
patches:
- path: argo-values.yaml
- path: argocd-cm-values.yaml
- path: ecr-sync.yaml
- path: actions-runner-controller-values.yaml
- path: argo-rollouts-values.yaml
