apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubecost
spec:
  releaseName: kubecost
  chart:
    spec:
      chart: cost-analyzer
      sourceRef:
        kind: HelmRepository
        name: kubecost
        namespace: flux-system
      version: v1.104.1
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # default values
  # https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml
  values:
    ingress:
      enabled: true
      https: true
      # className: alb
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/scheme: internal
        alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      paths: ["/*"]
      pathType: ImplementationSpecific
    podSecurityPolicy:
      enabled: false
    networkCosts:
      podSecurityPolicy:
        enabled: false
    prometheus:
      podSecurityPolicy:
        enabled: false
    grafana:
      rbac:
        pspEnabled: false