apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: keda
spec:
  releaseName: keda
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: flux-system
      version: 2.10.0
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # default values
  # https://github.com/kedacore/charts/blob/main/keda/values.yaml
  values:
    serviceAccount:
      create: true
      name: keda-operator
    podIdentity:
      aws:
        irsa:
          enabled: true
          audience: "sts.amazonaws.com"
          roleArn: "arn:aws:iam::174950171951:role/keda-service-account-rnd"