apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-rollouts
  namespace: argo-rollouts
spec:
  releaseName: argo-rollouts
  chart:
    spec:
      chart: argo-rollouts
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
      version: 2.34.1
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # https://github.com/argoproj/argo-helm/blob/main/charts/argo-rollouts/values.yaml
  values:
    dashboard:
      enabled: true
      readonly: false
      service:
        type: NodePort
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: alb
          alb.ingress.kubernetes.io/scheme: internal
          alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
        paths:
          - /
        