apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
- flux-slack-alert.yaml
- secret-store.yaml
patches:
- path: kubecost-values.yaml
# - path: robusta-values.yaml
- path: sops-annotation.yaml
