---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    name: kustomize-controller
  name: kustomize-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kustomize-controller
subjects:
  - kind: ServiceAccount
    name: kustomize-controller
    namespace: kustomize-controller