apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- namespace.yaml
- service-account.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
# - restart.yaml
