apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubectl-runner-role
  namespace: flux-system
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubectl-runner-rolebinding
  namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubectl-runner-role
subjects:
- kind: ServiceAccount
  name: kubectl-runner
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: kubectl-runner-pod
# spec:
#   serviceAccountName: kubectl-runner
#   restartPolicy: Never
#   containers:
#   - name: kubectl-container
#     image: bitnami/kubectl:latest
#     command:
#     - sh
#     - -c
#     - kubectl rollout restart deployment -n flux-system kustomize-controller
